
# This makefile assumes the GNU Multiprecision Library is installed where
# the linker can find it, and that the 'make' command has the usual defaults
# for building executables from C++ source code.

LDFLAGS = -l gmp
all: btd dtb
